name: deploy
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
      VITE_MCP_WS_URL: ${{ secrets.VITE_MCP_WS_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Create .env file
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env.production
          echo "VITE_MCP_WS_URL=${{ secrets.VITE_MCP_WS_URL }}" >> .env.production

      - name: Create Caddyfile from template
        run: |
          sed 's/{$DOMAIN}/${{ secrets.SSLIP_DOMAIN }}/g' Caddyfile.template > Caddyfile

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t barrier-free-kiosk-web . 
          docker tag barrier-free-kiosk-web ${{ secrets.DOCKER_HUB_USERNAME }}/barrier-free-kiosk-web:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/barrier-free-kiosk-web:${{ github.sha }}

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "Caddyfile,docker-compose.yml"
          target: "/home/ubuntu/app"

      - name: Create .env on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app
            echo "DOMAIN=${{ secrets.SSLIP_DOMAIN }}" > .env

      - name: SSH Connection and Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/app

            sudo docker-compose down
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/barrier-free-kiosk-web:${{ github.sha }}
            sudo docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/barrier-free-kiosk-web:${{ github.sha }} teamkim/barrier-free-kiosk-web:latest
            sudo docker system prune -af
            sudo docker-compose up -d
